name: Release

on: release

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cargo build --release
      - uses: JasonEtco/upload-to-release@master
        with:
          args: target/release/bot
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
