name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/bot
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
